#!/bin/sh
kill -2 $(ps aux | grep FVPN.app | awk '{print $2}') || true
launchctl unload /Library/LaunchAgents/com.fvpn.client.plist || true
launchctl unload /Library/LaunchDaemons/com.fvpn.service.plist || true

rm -rf /var/lib/fvpn || true
rm -f /var/log/fvpn.log || true
kextunload -b net.sf.tuntaposx.tap || true
kextunload -b net.sf.tuntaposx.tun || true
rm -rf /Library/Extensions/tap.kext || true
rm -rf /Library/Extensions/tun.kext || true
rm -f /Library/LaunchDaemons/net.sf.tuntaposx.tap.plist || true
rm -f /Library/LaunchDaemons/net.sf.tuntaposx.tun.plist || true
rm -rf /usr/local/bin/fvpn-openvpn || true
rm -rf /usr/local/bin/fvpn-service || true
